version: "3.0"
#PiHole for Ad-/Track-/Etc-Blocking
services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    networks:
      wirehole:
        ipv4_address: IP_ADDRESS #set a static IP for PiHole and edit .env accordingly
    depends_on:
      - "unbound"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    volumes:
      - '/data/wirehole/pihole/etc-pihole:/etc/pihole/'
      - '/data/wirehole/pihole/etc-dnsmasq.d:/etc/dsnmasq.d'
    env_file: .env
    cap_add:
      - "NET_ADMIN"
    restart: always
#Wireguard for use outside of network e.g. Mobile Devices
  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard
    depends_on:
      - "pihole"
    networks:
      wirehole:
        ipv4_address: IP_ADDRESS #set a static IP for Wireguard and edit .env accordingly
    ports:
      - "51820:51820/udp"
    volumes:
      - '/data/wirehole/wireguard/config/:/config'
      - '/data/wirehole/wireguard/config/wg_confs:/config/wg_confs/*.conf'
      - '/data/wirehole/wireguard/config/lib_modules:/lib/modules/'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: always
    env_file: .env
#Unbound as recursive DNS Server for PiHole
  unbound:
    container_name: unbound
    image: alpinelinux/unbound
#    platform: linux/arm64/v8 #if for example you want to use mvance/unbound on a pi(4)
    networks:
      wirehole:
        ipv4_address: IP_ADDRESS #set a static IP for unbound. Make sure to edit .env accordingly
    ports:
      - "5335:53/tcp"
      - "5335:53/udp"
    expose:
      - "5335"
#volumes created some errors for me so its ignored here. Volume for own config will be added but ignored soon.
#    volumes:
#      - "/data/wirehole/unbound/my_conf/:/opt/unbound/etc/unbound/"
    restart: always
    env_file: .env
networks:
  wirehole:
    name: wirehole-network
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: SUBNET_IP/24
          ip_range: IP_RANGE/24
          gateway: GATEWAY_IP